# 1 task

jobs:
- name: echo
  plan:
  - task: echo hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: sh
        args:
          - -c
          - |-
            echo Hello, world!
